server:
  error:
    include-binding-errors: always
    include-message: always
  port: '8080'
spring:
  data:
    mongodb:
      database: Registers
      uri: mongodb+srv://aracely10:aracely1008@cluster0.biago.mongodb.net/?retryWrites=true&w=majority

    application:
      name: measure-service
